// Raw CSV content for the seeded "Nordic Smart Home Electronics — EU"
// demo project. A connected-device manufacturer across 5 facilities,
// purpose-built to mirror Varun's reference dashboards in our framework
// (capacity bottleneck on Site A, forecast-accuracy spread, exec
// scorecard). Generated by src/sample-data/demo-electronics/generate.mjs.

import sku_master from "../sample-data/demo-electronics/sku_master.csv?raw";
import customer_master from "../sample-data/demo-electronics/customer_master.csv?raw";
import plant_master from "../sample-data/demo-electronics/plant_master.csv?raw";
import sales_history from "../sample-data/demo-electronics/sales_history.csv?raw";
import demand_forecast from "../sample-data/demo-electronics/demand_forecast.csv?raw";
import bom from "../sample-data/demo-electronics/bom.csv?raw";
import supplier from "../sample-data/demo-electronics/supplier.csv?raw";
import inventory from "../sample-data/demo-electronics/inventory.csv?raw";
import capacity from "../sample-data/demo-electronics/capacity.csv?raw";
import budget from "../sample-data/demo-electronics/budget.csv?raw";
import portfolio from "../sample-data/demo-electronics/portfolio.csv?raw";
import scorecard from "../sample-data/demo-electronics/scorecard.csv?raw";

export const DEMO_ELECTRONICS_CSV: Record<string, string> = {
  sku_master,
  customer_master,
  plant_master,
  sales_history,
  demand_forecast,
  bom,
  supplier,
  inventory,
  capacity,
  budget,
  portfolio,
  scorecard,
};
