// Scenario background narratives — the "situation" text shown on each
// project's Data Manager so a user can read what's going on and what to
// look for in the dashboard. Keyed by project name. (seed-convex.mjs keeps
// a copy for the CLI seed path.)

export const SCENARIO_BACKGROUNDS: Record<string, string> = {
  "SFC India — Sealings":
    "SFC Solutions India makes automotive sealing systems for Indian OEMs (TML, Maruti, Tata, M&M, Nissan, VW) across five plants. This is the real Mutares S&OP cadence: a monthly ICP (consensus plan) drives demand, an RCCP balances it against extrusion/mixing capacity, and the review pack tracks inventory, forecast accuracy & BIAS, and gap-closing actions. The Dec'22 baseline is ₹35.56 Cr. Watch the demand-vs-supply gap by family, forecast bias by SKU, and the inventory projection.",
  "ElectroTech Industries — EU":
    "ElectroTech Industries builds connected devices (smart-home hubs, industrial controllers, power modules, sensors) for EU B2B/B2C customers from three plants. The Karlsruhe SMT line is the bottleneck, and a Shenzhen capacitor supplier with a long lead time and weak reliability is the key material risk. A whole month (Nov-2022) is deliberately missing from sales history — a data-quality gap to exercise the AI data check. Watch the capacity overload and the data-gap flag in the Data Manager.",
  "Apex Brake Systems — México":
    "Apex Brake Systems is a Tier-1 brake manufacturer in México, carved out of a larger group and now run as a standalone turnaround. The 2024 plan is dominated by one shock: a major EV customer (VoltAuto) has ramped regenerative-braking caliper orders far faster than Monterrey can build them — both CNC cells are already over 100%, so a chunk of that demand is unmet and at risk. Meanwhile the legacy Drum Brakes business in Toluca is shrinking, yet the team keeps over-forecasting it and has built a mountain of finished drums (including a fully discontinued shoe) — inventory days there are an order of magnitude above target. A single Asian supplier for the ABS chip used in the new calipers has a 40-day lead time and weak reliability, putting the whole EV ramp at risk. Watch: the EV gap and its costed options (Supply), the Monterrey overload (Capacity), the drum over-forecast (Demand), and the Toluca SLOB + supplier risk.",
  "Nordic Smart Home Electronics — EU":
    "Nordic Smart Home Electronics is a connected-device maker (smart-home hubs, thermostats, gateways, power & sensing modules) running across five facilities — Site A (Tallinn, the lead SMT/PCBA plant), Site B (Kraków), Site C (Porto), Site D (Munich) and Site E (Gdańsk). This is the showcase scenario built to demonstrate the full S&OP cycle end-to-end. The story this cycle: Site A's SMT lines are the binding constraint and tip over 100% in several months, Site C runs slightly hot, while Sites D and E carry spare. On the demand side a handful of SKUs (Power Module X, Motion Sensor, Air Quality Monitor) carry poor forecast accuracy and BIAS that need an override decision, the plan runs a touch under budget on the Power & Sensing line, finished-goods inventory sits above target, and a discontinued Eco Plug Mini has become slow/obsolete stock. The WiFi/BT combo module from a Taiwanese supplier (35-day lead, weak reliability) is the key material risk. Walk it as: Process & checklist → Demand (accuracy/BIAS, accuracy-vs-revenue, forecast-vs-budget with manual override) → Capacity (unconstrained vs constrained, scenario comparison) → the two Executive scorecards.",
  "Helios Pumps & Compressors — Italy":
    "Helios Pumps & Compressors is an Italian industrial-equipment maker with three plants (Milan, Turin, Bologna). It's a classic mix-and-margin story: the big-volume Centrifugal Pumps line earns barely 16% contribution margin, while Vacuum Compressors (~45%) and Spare-Parts Kits (~53%) are far more profitable. Two things stand out this cycle. First, the only real supply gap sits on the low-margin pumps in Milan — so the question is whether it's even worth chasing. Second, the high-margin Vacuum Compressors in Turin are growing but being consistently under-forecast, leaving revenue and margin on the table; Turin also runs at ~99% of its planned capacity (though still under the physical ceiling), so any upside needs a capacity conversation. There's also a discontinued seal kit quietly tying up cash in Bologna, and the motor that feeds the profitable vacuum line comes from a single shaky supplier. Watch: contribution margin by family and the plan bridge (Demand), the dual-capacity view in Turin (Capacity), and SLOB + supplier risk (Supply).",
};
